server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dennisvanloon/spring-cloud-config
          search-paths:
            - 'configuration_files/{application}'
          default-label: master

message: Hello there, this is a message from the config in git